### ISSUE TITLE
Failed to init synth

### ISSUE THREAD

**Issue by antibyte** [uli/basicengine-firmware#2] opened 2018-06-30 18:01 UTC
Just finished building my Basic Engine board, so i tried the examples.
In Shmup as soon as a sound should play i get "Failed to init synth in 1340"
Soundfont is on the sd card.
If i type the Sound command from line 1340 after reset it works, after loading shmup.bas it throws the error.

Sokoban has some strange graphics issues, but i think its WIP ?

**Comment by uli** [comment] 2018-07-02 09:15
Wow, that was fast. :)

I think the problem is that I have never tried running shmup from a subdirectory; the sound font is loaded from a relative path. Could you try SOUND FONT "/sd/1mgm.sf2" and see if it works then?

[Sokoban exposes a CALL bug (see commit 9beca8e1c57), and needs fixes for the text window handling, which are also in the master branch since Saturday or something.]

**Comment by antibyte** [comment] 2018-07-02 19:43
Yes, SOUND FONT "/sd/1mgm.sf2" makes it work.

**Comment by uli** [comment] 2018-07-12 11:14
Fixed in v0.87-alpha.

**Closed by uli** 2018-07-12 11:14 UTC
